version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJANGO_ENV: production
    container_name: django
    volumes:
      - type: bind
        source: /sock
        target: /sock
      - type: volume
        source: static
        target: /app/staticfiles
    environment:
      DJANGO_ENV: production
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db

  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /sock
        target: /sock
      - type: volume
        source: static
        target: /static

  db:
    image: public.ecr.aws/docker/library/postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  static: